name: StartServer

on:
  repository_dispatch:
  workflow_dispatch:
  
concurrency: 
  group: jellyfin
  cancel-in-progress: true
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: JellyfinServer
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: rclone Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
      - name: rclone Config
        run: |
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG }}
          EOF
      - name: Jellyfin Install
        run: |
          sudo mkdir -p /home/runner/mount
          sudo apt install apt-transport-https
          wget -O - https://repo.jellyfin.org/jellyfin_team.gpg.key | sudo apt-key add -
          echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
          sudo apt update
          sudo apt install jellyfin
          sudo systemctl stop jellyfin
          sudo rm -r /var/lib/jellyfin
          sudo rm -r /etc/jellyfin
          sudo cp -R /home/runner/work/jellyfintest/jellyfintest/jellyfinconf/lib/jellyfin /var/lib/
          sudo cp -R /home/runner/work/jellyfintest/jellyfintest/jellyfinconf/etc/jellyfin /etc/
          sudo chmod 755 -R /var/lib/jellyfin/
          sudo chown -R jellyfin:jellyfin /etc/jellyfin/
          sudo chmod 755 -R /etc/jellyfin/
          sudo chown -R jellyfin:jellyfin /var/lib/jellyfin/
          mkdir cloudflare
          cd cloudflare
          wget https://github.com/cryptbphcoutlook/test123/raw/main/cloudflare/cloudflared-stable-linux-amd64.deb
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          cd ..
          cd ~/
          mkdir .cloudflared
          cd .cloudflared
          cat << EOF >> cert.pem
          ${{ secrets.CF_CERT }}
          EOF
          cd ..
          sudo rclone mount Media:/ /home/runner/mount/  --daemon --allow-other --cache-db-purge --buffer-size 32M --use-mmap --dir-cache-time 4h --drive-chunk-size 16M --timeout 1h --vfs-cache-mode minimal --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit 1G --fast-list
          sudo systemctl start jellyfin
          timeout 8m cloudflared --url localhost:8096 --hostname ${{ secrets.JELLYFIN_DOMAIN }} || ( [[ $? -eq 124 ]] && \echo "WARNING: Timeout reached for Jellyfin, but that's OK" )
          sudo systemctl stop jellyfin
          sudo rm -r /home/runner/work/jellyfintest/jellyfintest/jellyfinconf/
          cd /home/runner/work/jellyfintest/jellyfintest/
          mkdir jellyfinconf
          cd jellyfinconf
          mkdir etc
          mkdir lib
          cd lib
          sudo cp -R /var/lib/jellyfin /home/runner/work/jellyfintest/jellyfintest/jellyfinconf/lib/
          cd ..
          cd etc
          sudo cp -R /etc/jellyfin /home/runner/work/jellyfintest/jellyfintest/jellyfinconf/etc/
          cd ..
          sudo git config --global user.name 'argavnathjellyfin'
          sudo git config --global user.email 'argavnathjellyfin@users.noreply.github.com'
          sudo git add .
          sudo git commit -am "Config File"
          sudo git push
