name: debug

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  debug:
    runs-on: ubuntu-latest
    name: debug
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Jellyfin debug
        run: |
          mkdir cloudflare
          cd cloudflare
          wget https://github.com/cryptbphcoutlook/test123/raw/main/cloudflare/cloudflared-stable-linux-amd64.deb
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          cd ..
          mkdir aria
          cd aria
          sudo apt install tmux python3 aria2
          git clone https://github.com/ziahamza/webui-aria2.git
          tmux new -d \
              -c /home/runner/work/jellyfintest/jellyfintest/aria2/ \
              -s aria2rpc \
              'aria2c --enable-rpc --rpc-listen-all' \;
          tmux new -d \
                   -c /home/runner/work/jellyfintest/jellyfintest/aria2/webui-aria2/docs/ \
                   -s aria2webui \
                   'python3 -m http.server 8600' \;
          timeout 2m cloudflared --url localhost:8600 || ( [[ $? -eq 124 ]] && \echo "WARNING: Timeout reached for emby, but that's OK" )



