name: debug

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  debug:
    runs-on: ubuntu-latest
    name: debug
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Jellyfin debug
        run: |
          mkdir cloudflare
          cd cloudflare
          sudo apt install aria2
          wget https://github.com/cryptbphcoutlook/test123/raw/main/cloudflare/cloudflared-stable-linux-amd64.deb
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          cd ..
          aria2c --enable-rpc --rpc-listen-all --daemon
          mkdir aria
          cd aria
          git clone https://github.com/ziahamza/webui-aria2
          cd webui-aria2
          node node-server.js && timeout 15m cloudflared --url localhost:8888 || ( [[ $? -eq 124 ]] && \echo "WARNING: Timeout reached for emby, but that's OK" )



