name: debug

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  debug:
    runs-on: ubuntu-latest
    name: debug
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Jellyfin debug
        run: |
          mkdir cloudflare
          cd cloudflare
          wget https://github.com/cryptbphcoutlook/test123/raw/main/cloudflare/cloudflared-stable-linux-amd64.deb
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          cd ..
          sudo pip install pyload-ng
          sudo pyload --daemon
          timeout 2m cloudflared --url localhost:8000 || ( [[ $? -eq 124 ]] && \echo "WARNING: Timeout reached for emby, but that's OK" )



