name: debug

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  debug:
    runs-on: ubuntu-latest
    name: debug
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Jellyfin debug
        run: |
          mkdir cloudflare
          cd cloudflare
          wget https://github.com/cryptbphcoutlook/test123/raw/main/cloudflare/cloudflared-stable-linux-amd64.deb
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          cd ..
          mkdir aria
          cd aria
          sudo apt install python3 aria2
          sudo apt-get install unzip
          wget https://github.com/mayswind/AriaNg/releases/download/1.2.1/AriaNg-1.2.1-AllInOne.zip
          unzip  AriaNg-1.2.1-AllInOne.zip
          npm install gulp
          npm install
          gulp clean build
          timeout 2m cloudflared --url localhost:8080 || ( [[ $? -eq 124 ]] && \echo "WARNING: Timeout reached for emby, but that's OK" )



